# Generated by Django 2.2.5 on 2019-09-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190926_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(match='foo.*', path='/home/images', recursive=True),
        ),
    ]
