# Generated by Django 2.2.5 on 2019-09-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190926_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(allow_folders=True, match='project*', path='project/static/img', recursive=True),
        ),
    ]
